const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  options: () => ipcRenderer.invoke('db:options'),
  addOption: (key, value) => ipcRenderer.invoke('db:option:add', key, value),
  setOption: (key, arr) => ipcRenderer.invoke('db:option:set', key, arr),
  optionUsage: (key, value) => ipcRenderer.invoke('db:option:usage', key, value),
  deleteOption: (key, value) => ipcRenderer.invoke('db:option:delete', key, value),
  settingsGet: () => ipcRenderer.invoke('db:settings:get'),
  settingsSet: (patch) => ipcRenderer.invoke('db:settings:set', patch),
  strings: () => ipcRenderer.invoke('db:t'),
  projects: () => ipcRenderer.invoke('db:projects'),
  getProject: (id) => ipcRenderer.invoke('db:project:get', id),
  saveProject: (data) => ipcRenderer.invoke('db:project:save', data),
  deleteProject: (id) => ipcRenderer.invoke('db:project:delete', id),
  toggleProject: (id, done) => ipcRenderer.invoke('db:project:toggle', id, done),
  toggleTask: (projectId, taskId, done) => ipcRenderer.invoke('db:task:toggle', projectId, taskId, done),
  setIcon: (id, iconPath) => ipcRenderer.invoke('db:project:icon', id, iconPath),
  pickIcon: () => ipcRenderer.invoke('dialog:pickIcon'),
  pickBg: () => ipcRenderer.invoke('dialog:pickBg'),
  deadlines: () => ipcRenderer.invoke('db:deadlines'),
  stats: () => ipcRenderer.invoke('db:stats'),
  backup: () => ipcRenderer.invoke('db:backup'),
  restore: () => ipcRenderer.invoke('db:restore'),
  openUrl: (url) => ipcRenderer.invoke('shell:open', url),
  openX: (username) => ipcRenderer.invoke('shell:x', username),
  parseX: (v) => ipcRenderer.invoke('parse:x', v),
  copy: (text) => ipcRenderer.invoke('clipboard:write', String(text || '')),
});
