module.exports = {
  en: {
    appSubtitle: 'I promise to diligently farm airdrops again.',
    search: 'Search',
    showPending: 'Show pending only',
    todayLabel: '{v}',
    newProject: 'New project', editProject: 'Edit project',
    allNetworks: 'All networks', allCategories: 'All categories', allRanks: 'All ranks',
    network: 'Network', category: 'Category', rank: 'Rank',
    projects: 'Projects', done: 'Done', dailyProgress: 'Daily progress',
    noProjects: 'No projects yet',
    noProjectsHint: 'Add the first airdrop you are farming. Everything is stored locally in this app, nothing leaves your machine.',
    noMatches: 'No matches',
    noMatchesHint: 'Nothing matches the current search or filter. Clear them to see all projects.',
    clearFilters: 'Clear filters', addProject: 'Add project',
    tasks: 'tasks', markedDone: 'Marked done',
    website: 'Website', links: 'Links', identities: 'Identities', note: 'Note', status: 'Status',
    taskProgress: 'Task progress', taskDoneOf: '{a} of {b} tasks done',
    noTasks: 'No tasks recorded.',
    edit: 'Edit', delete: 'Delete project', cancel: 'Cancel', create: 'Create', saveChanges: 'Save changes',
    deleteConfirm: 'Delete {n} and all its data? This cannot be undone.',
    nameRequired: 'Project name is required',
    created: 'Created', lastEdited: 'Last edited',
    add: 'Add',
    cost: 'Cost', platform: 'Platform', walletApp: 'Wallet app',
    additionalLinks: 'Additional links', wallets: 'Wallets', xAccounts: 'X accounts', emails: 'Emails',
    tasksSection: 'Tasks',
    backup: 'Backup', restore: 'Restore',
    confirmDeleteOption: '"{v}" is used by {n} projects. Delete it anyway? The value will be removed from those projects.'
  },
  id: {
    appSubtitle: 'Saya berjanji akan rajin garap erdrop lagi.',
    search: 'Cari project, wallet, task',
    showPending: 'Tampilkan yang belum selesai',
    todayLabel: '{v}',
    newProject: 'Project baru', editProject: 'Edit project',
    allNetworks: 'Semua network', allCategories: 'Semua kategori', allRanks: 'Semua rank',
    network: 'Network', category: 'Kategori', rank: 'Rank',
    projects: 'Project', done: 'Selesai', dailyProgress: 'Progress harian',
    noProjects: 'Belum ada project',
    noProjectsHint: 'Tambahkan airdrop pertama yang sedang kamu kerjakan. Semua disimpan lokal di app ini, tidak ada yang keluar dari perangkatmu.',
    noMatches: 'Tidak ada hasil',
    noMatchesHint: 'Tidak ada yang cocok dengan pencarian atau filter saat ini. Hapus filter untuk melihat semua project.',
    clearFilters: 'Hapus filter', addProject: 'Tambah project',
    tasks: 'task', markedDone: 'Ditandai selesai',
    website: 'Website', links: 'Link', identities: 'Identitas', note: 'Catatan', status: 'Status',
    taskProgress: 'Progress task', taskDoneOf: '{a} dari {b} task selesai',
    noTasks: 'Belum ada task.',
    edit: 'Edit', delete: 'Hapus project', cancel: 'Batal', create: 'Buat', saveChanges: 'Simpan perubahan',
    deleteConfirm: 'Hapus {n} dan semua datanya? Ini tidak bisa dibatalkan.',
    nameRequired: 'Nama project wajib diisi',
    created: 'Dibuat', lastEdited: 'Terakhir diubah',
    add: 'Tambah',
    cost: 'Cost', platform: 'Platform', walletApp: 'Wallet app',
    additionalLinks: 'Link tambahan', wallets: 'Wallet', xAccounts: 'Akun X', emails: 'Email',
    tasksSection: 'Task',
    backup: 'Backup', restore: 'Restore',
    confirmDeleteOption: '"{v}" dipakai di {n} project. Tetap hapus? Nilainya akan dihapus dari project-project tersebut.'
  }
};;